version: "3.8"
services:
  springboot-app:
    image: vtha/user-service
    container_name: user-service
    restart: always
    build: .
    ports:
      - 8090:8080
    networks:
      - my-network
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/docker
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root125p

  mysqldb:
    image: mysql
    container_name: mysqldb
    ports:
      - 3307:3306
    networks:
      - my-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=docker
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root125p

networks:
  my-network: